import { CubeFaces } from "@/logic/newCube";
import { BlockProps } from "../components/Block/Block";
import { RIGHT, LEFT, TOP, BOTTOM, FRONT, BACK } from "@/logic/constants";

export type AllBlockColors = Record<0|1|2, Record<0|1|2, Record<0|1|2, BlockProps['initialFaceColors']>>>

export const mapAllBlockColors = (faces: CubeFaces): AllBlockColors  => ({
    0: {
        0: {
            0: { // bottom back left corner
                [RIGHT]: null,
                [LEFT]: faces.left[2][0],
                [TOP]: null,
                [BOTTOM]: faces.bottom[2][0],
                [FRONT]: null,
                [BACK]: faces.back[2][2],
            },
            1: { // bottom left edge
                [RIGHT]: null,
                [LEFT]: faces.left[2][1],
                [TOP]: null,
                [BOTTOM]: faces.bottom[1][0],
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // bottom front left corner
                [RIGHT]: null,
                [LEFT]: faces.left[2][2],
                [TOP]: null,
                [BOTTOM]: faces.bottom[0][0],
                [FRONT]: faces.front[2][0],
                [BACK]: null,                
            },
        },
        1: { 
            0: { // back left edge
                [RIGHT]: null,
                [LEFT]: faces.left[1][0],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[1][2],
            },
            1: { // left center
                [RIGHT]: null,
                [LEFT]: faces.left[1][1],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // front left edge
                [RIGHT]: null,
                [LEFT]: faces.left[1][2],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: faces.front[1][0],
                [BACK]: null,
            },
        },
        2: {
            0: { // top back left corner
                [RIGHT]: null,
                [LEFT]: faces.left[0][0],
                [TOP]: faces.top[0][0],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[0][2],
            },
            1: { // top left edge
                [RIGHT]: null,
                [LEFT]: faces.left[0][1],
                [TOP]: faces.top[1][0],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // top front left corner
                [RIGHT]: null,
                [LEFT]: faces.left[0][2],
                [TOP]: faces.top[2][0],
                [BOTTOM]: null,
                [FRONT]: faces.front[0][0],
                [BACK]: null,
            },
        },
    },
    1: {
        0: {
            0: { // bottom back edge
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[2][1],
                [FRONT]: null,
                [BACK]: faces.back[2][1],
            },
            1: { // bottom center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[1][1],
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // bottom front edge
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[0][1],
                [FRONT]: faces.front[2][1],
                [BACK]: null,                
            },
        },
        1: {
            0: { // back center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[1][1],
            },
            1: { // exact center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // front center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: faces.front[1][1],
                [BACK]: null,
            },
        },
        2: {
            0: { // top back center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: faces.top[0][1],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[0][1],
            },
            1: { // top center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: faces.top[1][1],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // top front center
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: faces.top[2][1],
                [BOTTOM]: null,
                [FRONT]: faces.front[0][1],
                [BACK]: null,
            },
        },
    },
    2: {
        0: {
            0: {// bottom back right corner
                [RIGHT]: faces.right[2][2],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[2][2],
                [FRONT]: null,
                [BACK]: faces.back[2][0],
            },
            1: {// bottom right edge
                [RIGHT]: faces.right[2][1],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[1][2],
                [FRONT]: null,
                [BACK]: null,
            },
            2: {// bottom front right corner
                [RIGHT]: faces.right[2][0],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: faces.bottom[0][2],
                [FRONT]: faces.front[2][2],
                [BACK]: null,                
            },
        },
        1: {
            0: {// back right edge
                [RIGHT]: faces.right[1][2],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[1][0],
            },
            1: {// right center
                [RIGHT]: faces.right[1][1],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {// front right edge
                [RIGHT]: faces.right[1][0],
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: faces.front[1][2],
                [BACK]: null,
            },
        },
        2: {
            0: {// top back right corner
                [RIGHT]: faces.right[0][2],
                [LEFT]: null,
                [TOP]: faces.top[0][2],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[0][0],
            },
            1: {// top right edge
                [RIGHT]: faces.right[0][1],
                [LEFT]: null,
                [TOP]: faces.top[1][2],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {// top front right corner
                [RIGHT]: faces.right[0][0],
                [LEFT]: null,
                [TOP]: faces.top[2][2],
                [BOTTOM]: null,
                [FRONT]: faces.front[0][2],
                [BACK]: null,
            },
        },
    },
})