import { CubeFaces } from "@/logic/newCube";
import { BlockProps } from "../components/Block/Block";
import { RIGHT, LEFT, TOP, BOTTOM, FRONT, BACK } from "@/logic/constants";

export type AllBlockColors = Record<0|1|2, Record<0|1|2, Record<0|1|2, BlockProps['initialFaceColors']>>>

export const mapAllBlockColors = (faces: CubeFaces): AllBlockColors  => ({
    0: {
        0: {
            0: { // bottom back left corner
                [RIGHT]: null,
                [LEFT]: faces.left[2][0],
                [TOP]: null,
                [BOTTOM]: faces.bottom[2][0],
                [FRONT]: null,
                [BACK]: faces.back[2][2],
            },
            1: { // bottom left edge
                [RIGHT]: null,
                [LEFT]: faces.left[2][1],
                [TOP]: null,
                [BOTTOM]: faces.bottom[1][0],
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // bottom front left corner
                [RIGHT]: null,
                [LEFT]: faces.left[2][2],
                [TOP]: null,
                [BOTTOM]: faces.bottom[0][0],
                [FRONT]: faces.front[2][0],
                [BACK]: null,                
            },
        },
        1: { 
            0: { // back left edge
                [RIGHT]: null,
                [LEFT]: faces.left[1][0],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[1][2],
            },
            1: { // left center
                [RIGHT]: null,
                [LEFT]: faces.left[1][1],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // front left edge
                [RIGHT]: null,
                [LEFT]: faces.left[1][2],
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: faces.front[1][0],
                [BACK]: null,
            },
        },
        2: {
            0: { // top back left corner
                [RIGHT]: null,
                [LEFT]: faces.left[0][0],
                [TOP]: faces.top[0][0],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: faces.back[0][2],
            },
            1: { // top left edge
                [RIGHT]: null,
                [LEFT]: faces.left[0][1],
                [TOP]: faces.top[1][0],
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: { // top front left corner
                [RIGHT]: null,
                [LEFT]: faces.left[0][2],
                [TOP]: faces.top[2][0],
                [BOTTOM]: null,
                [FRONT]: faces.front[0][0],
                [BACK]: null,
            },
        },
    },
    1: {
        0: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,                
            },
        },
        1: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
        },
        2: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
        },
    },
    2: {
        0: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,                
            },
        },
        1: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
        },
        2: {
            0: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            1: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
            2: {
                [RIGHT]: null,
                [LEFT]: null,
                [TOP]: null,
                [BOTTOM]: null,
                [FRONT]: null,
                [BACK]: null,
            },
        },
    },
})